kind = "web"
previewPath = "/"
title = "PlaceMIT"
version = "1.0.0"
id = "artifacts/placemit"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 19825

[services.development]
run = "pnpm --filter @workspace/placemit run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/placemit", "run", "build" ]
publicDir = "artifacts/placemit/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "19825"
BASE_PATH = "/"
